# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19O9NHhpA5TRZJlkUJUyxlZmFY25VKAfJ
"""

# src/scape/__init__.py
"""
scape: Semantic Complexity & Analysis Package

Subpackages:
- scape.scape_t: SCAPE-T (Encoder-only Transformer variant of SCAPE)
"""

# re-export the scape_t subpackage as a namespace
from . import scape_t

__all__ = ["scape_t"]